name: docker-swarm-deploy
author: Stephen M. Coakley <me@stephencoakley.com>
description: A GitHub Action that enables you to publish your app as a Docker stack to a remote Docker swarm.
inputs:
  remote_host:
    description: Docker host to connect to
    required: true
  ssh_public_key:
    description: SSH public key of the server
    required: false
  ssh_private_key:
    description: SSH private key to use to connect
    required: false
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  logout:
    description: 'Log out from the Docker registry at the end of a job'
    default: 'true'
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
